dist: "bionic"
language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
    - $HOME/tomcat
env:
  - CATALINA_PID=/tmp/tomcat.pid
addons:
  postgresql: "11"
services:
  - postgresql
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package -D skipTests
before_script:
  - mvn test
  - psql -f doc/db/00_create_db.sql -U postgres
  - psql -U postgres holarse < doc/db/01_as_postgres.sql
  - bash doc/ci/generate_tomcat.sh
  - bash $HOME/tomcat/bin/catalina.sh start && sleep 10
  - curl --silent --fail http://localhost:8080/
  - bash $HOME/tomcat/bin/catalina.sh stop -force
  - psql -U postgres holarse < doc/db/02_schemadata.sql
  - psql -U postgres holarse < doc/db/03_postdata.sql
script:
  - bash $HOME/tomcat/bin/catalina.sh start && sleep 10
  - bash doc/ci/test_basic_functionality.sh
  - mvn clean
