#!/bin/bash

# Functions
checkCommand() {
	# Check, if the command exists on the machine
	# args: command(str)
	local commandarg=$1
	if ! [ -x "$(command -v "$commandarg")" ]; then
		echo "Command $commandarg not found." >&2
		exit 1
	fi
	return 0
}
checkHash() {
	# Check, if the given hash is correct
	# args: completePathToFile(str), sha256Hash(str)
	local file=$1;
	local file_checksum=$2;

	sha_output=$(sha256sum "$file" | cut -d " " -f 1)

	if ! [ "$file_checksum" = "$sha_output" ]; then
		return 1
	fi
	return 0
}
checkFile() {
	# Check, if the file exists
	# args: completePathToFile(str)
	local file=$1
	if ! [ -e "$file" ]; then
		return 1
	fi
	return 0
}
checkDependency() {
	# Download the file, if not exists in the machine.
	# args: completePathToFile(str), downloadURL(str)
	local file_name=$1
	local downloadURL=$2
	if ! checkFile "$file_name"; then
		wget "$downloadURL" -O "$file_name"

		if ! checkFile "$file_name"; then

			return 1
		fi
	fi
	return 0
}
inspectFile() {
	# Check the file with the given hash
	# args: completePathToFile(str), downloadURL(str), Sha256Hash(str)
	local file=$1
	local downloadURL=$2
	local fileHash=$3

	if ! checkDependency "$file" "$downloadURL"; then
			echo "File($(basename "$file_name")) could not be downloaded." >&2
		exit 1
	fi

	if ! checkHash "$file" "$fileHash"; then
		echo "Invalid checksum for $(basename "$file")" >&2
		exit 1
	fi
	return 0
}


# Check, if the commands are available
commands=("wget" "sha256sum")
for command in "${commands[@]}"; do
	checkCommand "$command"
done

HTEMP="/tmp/holarseweb"
mkdir -p $HTEMP

# Payara
PAYARA_MICRO_JAR="payara-micro-5.181.jar"
PAYARA_SHA256="d1b9fee97fa01df802dbdb169ecbdfc7f4dad59792daace81ec6f7573b01a8cc"
PAYARA_DOWNLOAD_URL="https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/5.181/$PAYARA_MICRO_JAR"
inspectFile "$HTEMP/$PAYARA_MICRO_JAR" $PAYARA_DOWNLOAD_URL $PAYARA_SHA256

# Postgresql JDBC
POSTGRESQL_JDBC_JAR="postgresql-42.2.1.jar"
POSTGRESQL_JDBC_SHA256="d800ad754c7265b3bc06425d3ea0059a2a3226527226cecfd459f74b0be7d6ed"
POSTGRESQL_JDBC_DOWNLOAD_URL="https://jdbc.postgresql.org/download/$POSTGRESQL_JDBC_JAR"
inspectFile "$HTEMP/$POSTGRESQL_JDBC_JAR" $POSTGRESQL_JDBC_DOWNLOAD_URL $POSTGRESQL_JDBC_SHA256

COMPILE_PROJECT="mvn clean package"

# compile if argument is given
if [ "$1" = "compile" ]; then
    echo "kompiliere Projekt"
    $COMPILE_PROJECT
fi

PAYARA_OPTS="--disablephonehome --nocluster --rootDir /tmp/holarse-testing"

HOLARSE_WAR="target/HolarseWeb-1.0-SNAPSHOT.war"
# Compile Holarse-Web, if it is missing
if ! checkFile "$HOLARSE_WAR"; then
	echo "Holarse-Web will be compiled"
#	mvn clean package
fi

JAVA_BIN=$JAVA_HOME/bin/java

# Print variables
echo "JAVA            : $JAVA_BIN"
echo "JAVA_HOME              : $JAVA_HOME" 
echo "PAYARA_MICRO_JAR: $PAYARA_MICRO_JAR"
echo "PAYARA_OPTS     : $PAYARA_OPTS"
echo "HOLARE_WAR      : $HOLARSE_WAR"

COMMAND="$JAVA_BIN -jar "$HTEMP/$PAYARA_MICRO_JAR" $PAYARA_OPTS --addjars "$HTEMP/$POSTGRESQL_JDBC_JAR" --deploy $HOLARSE_WAR --domainconfig holarse-domain.xml"
$COMMAND
