#!/usr/bin/env bash
ARTICLE_DIR=$1

if [ -z "$APIUSER" ]; then
	echo "APIUSER not set"
	exit 1
fi

if [ -z "$APITOKEN" ]; then
	echo "APITOKEN not set"
	exit 2
fi

if [ -z "$ARTICLE_DIR" ]; then
	echo "Please specify import directory as parameter"
	exit 3
fi

BASE_FILES=$(find $ARTICLE_DIR/article-*.xml -type f | sort)

for i in $BASE_FILES; do
	echo "Importing $i"
	curl -u "$APIUSER":"$APITOKEN" -X POST -H "Accept: application/xml" -H "Content-Type: application/xml" http://holarse.localhost/api/import/articles -d @$i
done

