#!/usr/bin/env bash
source development/db.env

export POSTGRES_USER
export POSTGRES_DB

docker compose exec -T db psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "refresh materialized view mv_searchindex"
