update tags set taggroup_id = (select id from taggroups where name = 'ENGINE')
where name in (
    'Adobe AIR',
    'AGS',
    'Allegro',
    'Build Engine',
    'EDuke32',
    'FIFEngine',
    'Flash',
    'FNA',
    'Game Maker',
    'godot',
    'HTML5',
    'Irrlicht',
    'Ruby',
    'Java',
    'jMonkeyEngine',
    'jMonkeyVR',
    'Haxeflixel',
    'libgdx',
    'löve',
    'LWJGL',
    'Mono',
    'MonoGame',
    '.NET Core',
    'OpenFL',
    'OpenGL',
    'plib',
    'PyGame',
    'Python',
    'ResidualVM',
    'RPG Maker',
    'SDL',
    'Source-Engine',
    'Stratagus',
    'Torque3D',
    'Unity',
    'Unreal Engine 3',
    'Unreal Engine 4',
    'XNA',
    'zdoom',
    'OGRE3D',
    'Openra',
    'Panda3D'
);
