all:
  hosts:
    holarse-data:
      ansible_host: 192.168.122.152
      ansible_user: root
  vars:
    es_host: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    elasticsearch: true
    kibana: true
    postgresql: true
